"""
title: Ingest public API
layer: backend
public_api: yes
summary: Source-text ingestion — doc ids, backend selection (docling/native), markdown stripping, config.
"""
# Callers import FROM HERE, never from the private submodules. Keep __all__ tight.
from ._ids import doc_id
from ._markdown import markdown_to_text, collapse_table_padding
from ._source import SourceText, select_source
from ._config import (IngestConfig, load_ingest_config, VALID_BACKENDS, recommend_shards,
                      load_source_root)
from ._figures import (gate_figures, caption_is_useful, caption_type_is_furniture,
                       caption_cache_key, cache_last_wins, figure_sentinel, inline_figures,
                       image_markdown, inline_image_captions, FigureDecision, DENY_CLASSES,
                       ooxml_image_sentinel, ooxml_image_parts, inline_ooxml_images,
                       plan_office_images, OfficeImagePlan,
                       figure_outcome, figure_coverage, FigureCoverage,
                       FIG_CAPTURED, FIG_NO_CAPTION, FIG_GATED_TINY, FIG_GATED_DENY,
                       FIG_GATED_CHROME, FIG_GATED_DUP, FIG_GATED_OTHER,
                       FIG_LOST_BADCROP, FIG_LOST_BAIL)
from ._imageprobe import sniff_image_format, image_dimensions, IMAGE_EXTS
from ._media import resolve_media_refs, is_body_part
from ._coverage import (tokenize, coverage, CoverageReport, is_lossy, is_lossy_explained,
                        char_ngram_recall, html_to_text, strip_running_lines, words_in_bbox,
                        explain_gap, GapReport, merge_boxes)
from ._provenance import core_properties, pdf_info_meta, front_matter
from ._rawvocab import identifier_vocab, repair_split_tokens
from ._route import (route_format, classify_source, summarize_routes,
                     supported_formats, normalize_accept, unknown_formats, ext_of,
                     SourceClass, RouteScan, SUPPORTED_EXTS,
                     ROUTE_OOXML, ROUTE_DOCLING, ROUTE_PASSTHROUGH,
                     ROUTE_FENCE, ROUTE_LIBREOFFICE, ROUTE_UNSUPPORTED)
from ._ooxml_md import (docx_markdown, pptx_markdown, xlsx_markdown,
                        docx_source_text, pptx_source_text, xlsx_source_text,
                        ooxml_markdown, ooxml_source_text, svg_text, OOXML_MAIN_PARTS)
from ._recovery import (classify_failure, recovery_action,
                        plan_admission, order_todo,
                        FAIL_NONE, FAIL_OOM, FAIL_HANG, FAIL_DOCLING, FAIL_TRANSIENT,
                        FAIL_INPUT,
                        ACT_RETRY, ACT_ESCALATE, ACT_FALLBACK, ACT_BLACKLIST,
                        ADM_GROW, ADM_HOLD, ADM_SHRINK)

__all__ = [
    "tokenize",
    "coverage",
    "CoverageReport",
    "is_lossy",
    "is_lossy_explained",
    "char_ngram_recall",
    "html_to_text",
    "explain_gap",
    "GapReport",
    "merge_boxes",
    "strip_running_lines",
    "words_in_bbox",
    "core_properties",
    "pdf_info_meta",
    "front_matter",
    "identifier_vocab",
    "repair_split_tokens",
    "route_format",
    "classify_source",
    "summarize_routes",
    "supported_formats",
    "normalize_accept",
    "unknown_formats",
    "ext_of",
    "SourceClass",
    "RouteScan",
    "SUPPORTED_EXTS",
    "ROUTE_OOXML",
    "ROUTE_DOCLING",
    "ROUTE_PASSTHROUGH",
    "ROUTE_FENCE",
    "ROUTE_LIBREOFFICE",
    "ROUTE_UNSUPPORTED",
    "docx_markdown",
    "pptx_markdown",
    "xlsx_markdown",
    "docx_source_text",
    "pptx_source_text",
    "xlsx_source_text",
    "ooxml_markdown",
    "ooxml_source_text",
    "svg_text",
    "OOXML_MAIN_PARTS",
    "doc_id",
    "markdown_to_text",
    "collapse_table_padding",
    "SourceText",
    "select_source",
    "IngestConfig",
    "load_ingest_config",
    "load_source_root",
    "VALID_BACKENDS",
    "recommend_shards",
    "gate_figures",
    "caption_is_useful",
    "caption_type_is_furniture",
    "caption_cache_key",
    "cache_last_wins",
    "figure_sentinel",
    "inline_figures",
    "sniff_image_format",
    "image_dimensions",
    "IMAGE_EXTS",
    "resolve_media_refs",
    "is_body_part",
    "image_markdown",
    "inline_image_captions",
    "ooxml_image_sentinel",
    "ooxml_image_parts",
    "inline_ooxml_images",
    "plan_office_images",
    "OfficeImagePlan",
    "FigureDecision",
    "DENY_CLASSES",
    "figure_outcome",
    "figure_coverage",
    "FigureCoverage",
    "FIG_CAPTURED",
    "FIG_NO_CAPTION",
    "FIG_GATED_TINY",
    "FIG_GATED_DENY",
    "FIG_GATED_CHROME",
    "FIG_GATED_DUP",
    "FIG_GATED_OTHER",
    "FIG_LOST_BADCROP",
    "FIG_LOST_BAIL",
    "classify_failure",
    "recovery_action",
    "plan_admission",
    "order_todo",
    "FAIL_NONE",
    "FAIL_OOM",
    "FAIL_HANG",
    "FAIL_DOCLING",
    "FAIL_TRANSIENT",
    "FAIL_INPUT",
    "ACT_RETRY",
    "ACT_ESCALATE",
    "ACT_FALLBACK",
    "ACT_BLACKLIST",
    "ADM_GROW",
    "ADM_HOLD",
    "ADM_SHRINK",
]
