#!/usr/bin/env python3
"""Package LibreOffice INTO this tree so the office lane always has it.

The OOXML lane is deterministic and lossless for docx/pptx/xlsx on its own, but the
LibreOffice/legacy formats (odt/ods/odp, doc/xls/ppt, rtf) need ``soffice`` to
pre-convert to their OOXML sibling first, and emf/wmf figure rendering uses it too.
Rather than depend on a system install (which may be absent), this materializes a
self-contained, RELOCATABLE LibreOffice under ``<repo>/vendor/libreoffice`` that
``office_convert.find_soffice`` discovers automatically — no PATH, no env var.

It is:

  * generic & relocatable — the launcher derives every path from its own location,
    so the tree can move without edits (no ``/scratch`` baked in);
  * reproducible — it extracts from a set of ``.rpm`` files (no-root, rpm2cpio|cpio),
    and CARRIES those rpms in-tree (``vendor/libreoffice/rpms``) so a later
    ``--force`` re-materializes with no external source;
  * idempotent & safe to run twice — if a working ``soffice`` is already vendored it
    exits without doing anything unless ``--force`` is given.

First run seeds the carried rpms from an external source::

    python3 scripts/setup_libreoffice.py --rpms /path/to/libreoffice/rpms

Afterwards (rpms already carried) just::

    python3 scripts/setup_libreoffice.py            # no-op if already installed
    python3 scripts/setup_libreoffice.py --force    # rebuild root/ from carried rpms

Runs on the plain 3.6 host python (stdlib only). Needs ``rpm2cpio`` and ``cpio``.
"""
import argparse
import glob
import os
import shutil
import subprocess
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_REPO = os.path.dirname(_HERE)
VENDOR = os.path.join(_REPO, "vendor", "libreoffice")
ROOT = os.path.join(VENDOR, "root")            # extracted RPM filesystem (regenerable)
RPMS = os.path.join(VENDOR, "rpms")            # carried .rpm source (seeds re-extract)
LOHOME = os.path.join(VENDOR, "lohome")        # LibreOffice HOME / user profile
BIN = os.path.join(VENDOR, "bin")
WRAPPER = os.path.join(BIN, "soffice")

# Where soffice lands inside the extracted RPM tree (mirrors the RPM layout).
_PROG_REL = "root/usr/lib64/libreoffice/program"

# A relocatable launcher: every path derives from the script's own directory, so
# moving <repo>/vendor/libreoffice anywhere keeps it working. Written to bin/soffice.
_WRAPPER_SH = """#!/bin/sh
# Relocatable LibreOffice launcher. Generated by scripts/setup_libreoffice.py --
# do not hand-edit; all paths derive from this file's location.
here="$(cd "$(dirname "$0")/.." && pwd)"
prog="$here/root/usr/lib64/libreoffice/program"
export LD_LIBRARY_PATH="$prog:$here/root/usr/lib64:$LD_LIBRARY_PATH"
export HOME="$here/lohome"
exec "$prog/soffice" -env:UserInstallation="file://$here/lohome/.lo_profile" "$@"
"""


def _tool(name):
    # type: (str) -> str
    return shutil.which(name) or ""


def is_installed():
    # type: () -> bool
    """True if a vendored soffice launcher exists, is executable, and its target
    binary is present (a half-extracted tree is NOT installed)."""
    prog = os.path.join(VENDOR, _PROG_REL, "soffice")
    return (os.path.isfile(WRAPPER) and os.access(WRAPPER, os.X_OK)
            and os.path.isfile(prog))


def _seed_rpms(external_dir):
    # type: (str) -> int
    """Copy external ``.rpm`` files into the carried in-tree rpms dir. Returns count."""
    os.makedirs(RPMS, exist_ok=True)
    n = 0
    for rpm in sorted(glob.glob(os.path.join(external_dir, "*.rpm"))):
        dest = os.path.join(RPMS, os.path.basename(rpm))
        if not os.path.isfile(dest):
            shutil.copy2(rpm, dest)
        n += 1
    return n


def _extract_rpm(rpm, into):
    # type: (str, str) -> None
    """no-root extraction of one rpm into ``into`` via ``rpm2cpio <rpm> | cpio -idmu``."""
    p1 = subprocess.Popen(["rpm2cpio", rpm], stdout=subprocess.PIPE)
    p2 = subprocess.Popen(["cpio", "-idmu", "--quiet"], stdin=p1.stdout, cwd=into,
                          stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    p1.stdout.close()
    _out, err = p2.communicate()
    if p2.returncode not in (0, None):
        raise RuntimeError("cpio failed on %s: %s"
                           % (os.path.basename(rpm), (err or b"").decode("utf-8", "replace")))


def _write_wrapper():
    # type: () -> None
    os.makedirs(BIN, exist_ok=True)
    with open(WRAPPER, "w") as f:
        f.write(_WRAPPER_SH)
    os.chmod(WRAPPER, 0o755)


def _verify():
    # type: () -> str
    """Run the vendored soffice ``--version``; return the version line or raise."""
    out = subprocess.check_output([WRAPPER, "--version"], stderr=subprocess.STDOUT,
                                  timeout=120)
    return out.decode("utf-8", "replace").strip().splitlines()[0]


def install(rpms_src=None, force=False):
    # type: (str, bool) -> int
    """Materialize the vendored LibreOffice. Returns a process exit code."""
    if not _tool("rpm2cpio") or not _tool("cpio"):
        sys.stderr.write("setup-libreoffice: need rpm2cpio and cpio on PATH.\n")
        return 3

    if is_installed() and not force:
        try:
            print("setup-libreoffice: already installed -> %s (%s)" % (WRAPPER, _verify()))
            return 0
        except (subprocess.CalledProcessError, subprocess.TimeoutExpired, OSError):
            sys.stderr.write("setup-libreoffice: vendored soffice present but not "
                             "runnable; rebuilding.\n")

    # Seed carried rpms from an external source the first time (or when told to).
    if rpms_src:
        if not os.path.isdir(rpms_src):
            sys.stderr.write("setup-libreoffice: --rpms %r is not a directory.\n" % rpms_src)
            return 2
        n = _seed_rpms(rpms_src)
        print("setup-libreoffice: carried %d rpm(s) into %s" % (n, RPMS))

    rpm_files = sorted(glob.glob(os.path.join(RPMS, "*.rpm")))
    if not rpm_files:
        sys.stderr.write("setup-libreoffice: no rpms carried in %s and none supplied. "
                         "Seed once with --rpms /path/to/libreoffice/rpms "
                         "(obtain via e.g. `dnf download --resolve libreoffice-core`).\n" % RPMS)
        return 2

    # Rebuild the extracted tree from scratch so a re-run is deterministic.
    if os.path.isdir(ROOT):
        shutil.rmtree(ROOT, ignore_errors=True)
    os.makedirs(ROOT)
    print("setup-libreoffice: extracting %d rpm(s) -> %s" % (len(rpm_files), ROOT))
    for rpm in rpm_files:
        _extract_rpm(rpm, ROOT)

    prog = os.path.join(VENDOR, _PROG_REL, "soffice")
    if not os.path.isfile(prog):
        sys.stderr.write("setup-libreoffice: extraction did not yield %s -- are these "
                         "LibreOffice rpms?\n" % prog)
        return 4

    os.makedirs(LOHOME, exist_ok=True)
    _write_wrapper()
    try:
        ver = _verify()
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired, OSError) as e:
        sys.stderr.write("setup-libreoffice: vendored soffice failed to run: %s\n" % e)
        return 5
    print("setup-libreoffice: installed %s" % ver)
    print("setup-libreoffice: office_convert.find_soffice will now discover %s" % WRAPPER)
    return 0


def main(argv=None):
    # type: (list) -> int
    ap = argparse.ArgumentParser(
        description="Package a self-contained, relocatable LibreOffice under "
                    "<repo>/vendor/libreoffice so the office lane always has soffice.")
    ap.add_argument("--rpms", default="", help="external directory of LibreOffice .rpm "
                    "files to seed the in-tree source (needed only the first time)")
    ap.add_argument("--force", action="store_true",
                    help="rebuild even if a working vendored soffice already exists")
    ap.add_argument("--uninstall", action="store_true",
                    help="remove <repo>/vendor/libreoffice entirely and exit")
    args = ap.parse_args(argv)

    if args.uninstall:
        shutil.rmtree(VENDOR, ignore_errors=True)
        print("setup-libreoffice: removed %s" % VENDOR)
        return 0

    return install(rpms_src=(args.rpms.strip() or None), force=args.force)


if __name__ == "__main__":
    sys.exit(main())
